### ISSUE TITLE
PHP, git in Android

### ISSUE THREAD

**Issue by dhirenjaypal** [ziracms/editor#1]
please add php binary and git binary for android app.
also add terminal.
i am android user, i don't have pc right now to build app

**Comment by ziracms** [comment]
Execute permissions was removed from data folder in Android 10 (API 29+) https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission
Currently I don't know is there a workaround for it, but I will check.
At the moment you can install php in Termux and run built-in webserver from it.

**Comment by dhirenjaypal** [comment]
thank you, i am already using termux.

i just thought it would be good to use it without opening termux.
